# Импортируем библиотеки

In [3]:
import pandas as pd
import numpy as np

# Закгружаем датасет

In [4]:
data = pd.read_csv('train.csv')
data


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [5]:
data.info

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                   

# Обработаем данные

In [6]:
column_target = ['Survived']

In [7]:
print('Не определен пол у', data['Sex'].isnull().sum())
for i in range(len(data['Sex'])):
    if data.loc[i, 'Sex'] == 'male':
        data.loc[i, 'Sex'] = 1
    if data.loc[i, 'Sex'] == 'female':
        data.loc[i, 'Sex'] = 0
data

Не определен пол у 0


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris   1  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   0  38.0      1   
2                               Heikkinen, Miss. Laina   0  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)   0  35.0      1   
4                             Allen, Mr. William Henry   1  35.0      0   
..                                                 ...  ..   ...    ...   
886                              Montvila, Rev. Juozas   1  27.0      0   
887                       Graham, Miss. Margaret Edith   0  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"   0   NaN      1   
889                              Behr, Mr. Karl Howell   1  26.0      0   
890                                Dooley, Mr. Patrick   1  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

## Проверим пропуски в столбиках

In [8]:
print('Нет данных о выживании у', data['Survived'].isnull().sum())
print('Нет данных о классе обслуживания у', data['Pclass'].isnull().sum())
print('Нет данных о возрасте у', data['Age'].isnull().sum())
print('Нет данных о классе каюты у', data['Fare'].isnull().sum())
print('Нет данных об их детях у', data['Parch'].isnull().sum())
print('Нет данных об их супругах у', data['SibSp'].isnull().sum())
data

Нет данных о выживании у 0
Нет данных о классе обслуживания у 0
Нет данных о возрасте у 177
Нет данных о классе каюты у 0
Нет данных об их детях у 0
Нет данных об их супругах у 0


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris   1  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   0  38.0      1   
2                               Heikkinen, Miss. Laina   0  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)   0  35.0      1   
4                             Allen, Mr. William Henry   1  35.0      0   
..                                                 ...  ..   ...    ...   
886                              Montvila, Rev. Juozas   1  27.0      0   
887                       Graham, Miss. Margaret Edith   0  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"   0   NaN      1   
889                              Behr, Mr. Karl Howell   1  26.0      0   
890                                Dooley, Mr. Patrick   1  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

## Заполним пропуски в возрасте на медианные

In [9]:
#print(data)
median = np.nanmedian(a=data['Age'], axis=0)
print(median)
data['Age'] = data['Age'].fillna(median)
#data['Age'].median

28.0


In [10]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris   1  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   0  38.0      1   
2                               Heikkinen, Miss. Laina   0  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)   0  35.0      1   
4                             Allen, Mr. William Henry   1  35.0      0   
..                                                 ...  ..   ...    ...   
886                              Montvila, Rev. Juozas   1  27.0      0   
887                       Graham, Miss. Margaret Edith   0  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"   0  28.0      1   
889                              Behr, Mr. Karl Howell   1  26.0      0   
890                                Dooley, Mr. Patrick   1  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

# Выберем данные скорее всего выжны для выживания

In [11]:
columns_train = ['Pclass', 'Sex', 'Age', 'Fare', 'Parch', 'SibSp']
X = data[columns_train]
Y = data[column_target]
X

Pclass Sex   Age     Fare  Parch  SibSp
0         3   1  22.0   7.2500      0      1
1         1   0  38.0  71.2833      0      1
2         3   0  26.0   7.9250      0      0
3         1   0  35.0  53.1000      0      1
4         3   1  35.0   8.0500      0      0
..      ...  ..   ...      ...    ...    ...
886       2   1  27.0  13.0000      0      0
887       1   0  19.0  30.0000      0      0
888       3   0  28.0  23.4500      2      1
889       1   1  26.0  30.0000      0      0
890       3   1  32.0   7.7500      0      0

[891 rows x 6 columns]

# Разбиваем выборку на тестовую

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state=42)

print(
    f'Разделение на выборки:\n'
    f'training: {(100 * len(X_train) / len(X)):.2f} %\n'
    f'testing: {(100 * len(X_test) / len(Y)):.2f} %\n'
)

Разделение на выборки:
training: 69.92 %
testing: 30.08 %



# Подключаем метод и обучаем ЛИНЕЙНОЙ РЕГРЕССИЕЙ БЕЗ ГИПЕРПАРАМЕТРОВ

In [13]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train, y_train)
print("intercept")
print(model.intercept_)
print("коэффициент регрессии")
print(model.coef_)

intercept
[1.22078791]
коэффициент регрессии
[[-0.15009393 -0.50613636 -0.00523429  0.00053998 -0.02293541 -0.03800437]]


# Точность

In [77]:
y_pred = model.predict(X_test)
y_pred=np.around(y_pred)
y_pred = y_pred.astype(np.int32)
y_pred

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [79]:
model.score(X_test, y_test)

0.4451024109841405

In [78]:
from sklearn import metrics

cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[134,  23],
       [ 34,  77]], dtype=int64)

### Функция подсчета точности

In [106]:
def currency (really, predict):
    count=0
    y_t=np.copy(really)
    for i in range(len(really)):
        if np.array_equal(predict[i], y_t[i]):
            count+=1
    return count/len(really)
print(currency(y_test,y_pred))

0.7873134328358209


# Уберем данные о детях и о супругах

In [98]:
columns_train_2 = ['Pclass', 'Sex', 'Age', 'Fare', ]
X_2 = data[columns_train_2]
Y_2 = data[column_target]
X_2
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_2, Y_2, test_size=0.30, random_state=42)

In [99]:
model_2=LinearRegression()
model_2.fit(X_train_2, y_train_2)
print("intercept 2")
print(model_2.intercept_)
print("коэффициент регрессии 2")
print(model_2.coef_)

intercept 2
[1.19762607]
коэффициент регрессии 2
[[-1.63612825e-01 -4.92117210e-01 -4.36100548e-03  2.09989177e-04]]


In [100]:
y_pred_2 = model_2.predict(X_test_2)
y_pred_2 = np.around(y_pred_2)
y_pred_2 = y_pred_2.astype(np.int32)
model_2.score(X_test_2, y_test_2)

0.4351764221180533

In [107]:
print(currency(y_test_2,y_pred_2))

0.7947761194029851


# Точность улучшилась

# Применим метод Ridge

In [108]:
from sklearn import linear_model
ridge = linear_model.Ridge(alpha=0.5)
ridge.fit(X_train, y_train)
print("intercept 3")
print(ridge.intercept_)
print("коэффициент регрессии 3")
print(ridge.coef_)


intercept 3
[1.21906007]
коэффициент регрессии 3
[[-0.14996426 -0.50418    -0.00523656  0.00054335 -0.02264586 -0.03803365]]


In [109]:
y_pred_3 = ridge.predict(X_test)
y_pred_3=np.around(y_pred_3)
y_pred_3 = y_pred_3.astype(np.int32)
ridge.score(X_test, y_test)

0.4449624862522359

In [130]:
y_pred_3 = ridge.predict(X_test)
y_pred_3=np.around(y_pred_3)
y_pred_3 = y_pred_3.astype(np.int32)
print(currency(y_test,y_pred_3))

0.7947761194029851


# Обучим на вторых данных

In [111]:
ridge_2 = linear_model.Ridge(alpha=0.5)
ridge_2.fit(X_train_2, y_train_2)
print("intercept 4")
print(ridge_2.intercept_)
print("коэффициент регрессии 4")
print(ridge_2.coef_)
X_test_2

intercept 4
[1.19593863]
коэффициент регрессии 4
[[-1.63417429e-01 -4.90321078e-01 -4.36435171e-03  2.14538569e-04]]


Pclass Sex   Age     Fare
709       3   1  28.0  15.2458
439       2   1  31.0  10.5000
840       3   1  20.0   7.9250
720       2   0   6.0  33.0000
39        3   0  14.0  11.2417
..      ...  ..   ...      ...
821       3   1  27.0   8.6625
633       1   1  28.0   0.0000
456       1   1  65.0  26.5500
500       3   1  17.0   8.6625
430       1   1  28.0  26.5500

[268 rows x 4 columns]

In [112]:
y_pred_4 = ridge_2.predict(X_test_2)
np.around(y_pred_4)
ridge_2.score(X_test_2, y_test_2)

0.43503304779650953

In [113]:
#y_pred_4 = ridge.predict(X_test_2)
y_pred_4=np.around(y_pred_4)
y_pred_4 = y_pred_4.astype(np.int32)
print(currency(y_test_2,y_pred_4))

0.7947761194029851


# Точность ухудшилась

# Обучим методом Lasso

In [114]:
lasso = linear_model.Lasso(alpha=0.1)
lasso.fit(X_train, y_train)
print("intercept 5")
print(lasso.intercept_)
print("коэффициент регрессии 5")
print(lasso.coef_)

intercept 5
[0.40836257]
коэффициент регрессии 5
[-0.         -0.05197419 -0.00253836  0.00220651  0.         -0.        ]


In [116]:
y_pred_5 = lasso.predict(X_test)
np.around(y_pred_5)
lasso.score(X_test, y_test)

0.13301143381367053

In [118]:
y_pred_5 = ridge.predict(X_test)
y_pred_5=np.around(y_pred_5)
y_pred_5 = y_pred_5.astype(np.int32)
print(currency(y_test,y_pred_5))

0.7947761194029851


# На вторых данных

In [119]:
lasso_2 = linear_model.Lasso(alpha=0.1)
lasso_2.fit(X_train_2, y_train_2)
print("intercept 6")
print(lasso_2.intercept_)
print("коэффициент регрессии 6")
print(lasso_2.coef_)

intercept 6
[0.40836257]
коэффициент регрессии 6
[-0.         -0.05197419 -0.00253836  0.00220651]


In [120]:
y_pred_6 = lasso_2.predict(X_test_2)
np.around(y_pred_6)
lasso_2.score(X_test_2, y_test_2)

0.13301143381367053

In [133]:
y_pred_6 = ridge.predict(X_test)
y_pred_6=np.around(y_pred_3)
y_pred_6 = y_pred_6.astype(np.int32)
print(currency(y_test_2,y_pred_6))

0.7947761194029851
